FORMAT: 1A

# ANN API v1.0

Ann has a simple API allowing consumers (in this case a front-end application)
to access notes, notebooks and tags.

# Group Notebook

## Notebook Collection [/notebooks]

### List All Notebooks [GET]

+ Response 200 (application/json)

    + Attributes (array[Notebook])

### Create a New Notebook [POST]

+ Request  (application/json)

        {
          "name": "React"
        }

+ Response 201 (application/json)

    + Attributes (Notebook)


## Notebook [/notebooks/{id}]

+ Parameters
  + id (number) - ID of the Notebook in the form of an integer

### View a Notebook Detail [GET]

+ Response 200 (application/json)

    + Attributes (Notebook)

### Update a Notebook Detail [PUT]

+ Request  (application/json)

    + Attributes (Notebook)

### Delete a Notebook [DELETE]

+ Response 204


# Group Note

## Note Collection [/notebooks/{notebook_id}/notes]

+ Parameters
  + notebook_id (number) - ID of the Notebook in the form of an integer

### List All Notes within a Notebook [GET]

+ Response 200 (application/json)

    + Attributes (array[Note])


### Create a New Note within the specified Notebook [POST]

+ Request  (application/json)

        {
            "title": "How to train dragons",
            "body": "Super long string here"
        }


+ Response 201 (application/json)

    + Attributes (Note)



## Note [/notebooks/{notebook_id}/notes/{id}]

+ Parameters
    + notebook_id (number) - ID of the Notebook in the form of an integer
    + id (number) - ID of the Note in the form of an integer

### View a Note Detail [GET]

+ Response 200 (application/json)

    + Attributes (Note)



## Data Structures

### User
The owner of all notes

#### Properties

- full_name: Jon Snow (required)
- email: `Jon@know-nothing.com` (required)


### Note
A note taken by the user

#### Properties

- title: How to train your dragon (required)
- body: A super long string (string)
- author (User, required)
- notebook (Notebook, required)


### RichText
The content/body of a note

#### Properties

- note (Note, required)
- body (required)


### Notebook
A simple way to keep notes organized

#### Properties

- name: Recipes (required)
- created_at: `2014-11-11T08:40:51.620Z` (required)
- updated_at: `2014-11-11T08:40:51.620Z` (required)


### Tag
A mark for notes.

#### Properties

- name: ruby (string, required)
